/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_hearttouch_hotfixsamples_NdkJniTestUtil */

#ifndef _Included_com_netease_hearttouch_hotfixsamples_NdkJniTestUtil
#define _Included_com_netease_hearttouch_hotfixsamples_NdkJniTestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netease_hearttouch_hotfixsamples_NdkJniTestUtil
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_netease_hearttouch_hotfixsamples_NdkJniTestUtil_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
